apiVersion: v2
name: osac-aap
description: OSAC AAP integration - bootstrap and configuration
type: application
version: 0.0.13-nightly.20260924.81b27f6.44.1
appVersion: 0.0.13-nightly.20260924.81b27f6.44.1
