apiVersion: v2
name: osac-aap
description: OSAC AAP integration - bootstrap and configuration
type: application
version: 0.0.13-nightly.20260925.81b27f6.45.1
appVersion: 0.0.13-nightly.20260925.81b27f6.45.1
