apiVersion: v2
name: osac-operator
description: OSAC Operator - manages OSAC custom resources
type: application
version: 0.0.12-nightly.20260925.81b27f6.45.1
appVersion: 0.0.12-nightly.20260925.81b27f6.45.1
